sudo: required
services:
  - docker

before_install:
  - docker build -t nigelfrnds/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nigelfrnds/react-test npm test

after_success:
  - docker build -t nigelfrnds/complex-client ./client
  - docker build -t nigelfrnds/complex-nginx ./nginx
  - docker build -t nigelfrnds/complex-server ./server
  - docker build -t nigelfrnds/complex-worker ./worker

  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nigelfrnds/complex-client
  - docker push nigelfrnds/complex-nginx
  - docker push nigelfrnds/complex-server
  - docker push nigelfrnds/complex-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ca-central-1
  app: docker-complex-test
  env: DockerComplexTest-env
  bucket_name: elasticbeanstalk-ca-central-1-901472457604
  bucket_path: docker-complex-test
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



